<?xml version="1.0" encoding="UTF-8"?>
<project
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.codeminders</groupId>
    <artifactId>hidapi</artifactId>
    <packaging>jar</packaging>
    <name>Java API for working with Human Interface USB Devices (HID)</name>
    <version>2.0.0-SNAPSHOT</version>
    <properties>
        <java-version>17</java-version>
        <enforcer.jdk-version>[${java-version},)</enforcer.jdk-version>
        <enforcer.maven-version>[3.6.3,)</enforcer.maven-version>

        <maven-compiler-plugin.version>3.14.0</maven-compiler-plugin.version>
        <maven-enforcer-plugin.version>3.5.0</maven-enforcer-plugin.version>

        <slf4j.version>1.7.32</slf4j.version>
        <junit.version>4.13.2</junit.version>
    </properties>
    <description>JNI wrapper around C/C++ HIDAPI library providing simple java
        API to work with devices such as USB gamepads, joysticks, keyboards etc.</description>
    <url>http://code.google.com/p/javahidapi</url>
    <licenses>
        <license>
            <name>New BSD License</name>
            <url>http://opensource.org/licenses/BSD-3-Clause</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <scm>
        <connection>scm:hg:http://code.google.com/p/javahidapi</connection>
        <developerConnection>scm:hg:https://code.google.com/p/javahidapi</developerConnection>
        <url>http://code.google.com/p/javahidapi</url>
    </scm>
    <developers>
        <developer>
            <id>lord</id>
            <name>Vadim Zaliva</name>
            <email>lord@codeminders.com</email>
        </developer>
        <developer>
            <id>Alexander Sova</id>
            <name>Vadim Zaliva</name>
            <email>bird@codeminders.com</email>
        </developer>
        <developer>
            <id>dshmyga</id>
            <name>Denis Shmyga</name>
            <email>dshmyga@codeminders.com</email>
        </developer>
    </developers>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-log4j12</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </dependency>
    </dependencies>
    <build>
        <sourceDirectory>src</sourceDirectory>
        <testSourceDirectory>java-test/java</testSourceDirectory>
        <resources>
            <resource>
                <directory>lib</directory>
                <includes>
                    <include>native/**</include>
                </includes>
            </resource>
        </resources>
        <testResources>
            <testResource>
                <directory>java-test/resources</directory>
                <includes>
                    <include>**</include>
                </includes>
            </testResource>
        </testResources>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <source>${java-version}</source>
                        <target>${java-version}</target>
                    </configuration>
                </plugin>
                <plugin>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${maven-enforcer-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>min-requirement</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireMavenVersion>
                                    <version>${enforcer.maven-version}</version>
                                </requireMavenVersion>
                                <requireJavaVersion>
                                    <version>${enforcer.jdk-version}</version>
                                </requireJavaVersion>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
